import 'dart:convert';
import 'dart:io';
import 'package:flutter/material.dart';
import 'package:path/path.dart' as p;
import 'package:path_provider/path_provider.dart';
import 'package:funswap/core/services/preferences_service.dart';

final ValueNotifier<String> appLanguageNotifier = ValueNotifier<String>('English');

class LocalizationService {
  static const String keyUz = 'Uzbekcha';
  static const String keyEn = 'English';
  static const String keyRu = 'Русский';

  static final Map<String, Map<String, String>> _translations = {
    keyUz: {
      'tab_home': 'Bosh sahifa',
      'tab_files': 'Fayllar',
      'tab_favorites': 'Yaqinlar',
      'tab_profile': 'Profil',
      'loading': 'Yuklanmoqda...',
      'file_converter': 'Fayl Konverteri',
      'onboarding_skip': 'O\'tkazib yuborish',
      'onboarding_next': 'Keyingi',
      'onboarding_start': 'Boshlash',
      'onboarding_title_1': 'Fayllarni istalgan\nformatga konvertatsiya\nqiling',
      'onboarding_subtitle_1': 'Hujjat, rasm, audio, video va boshqa\nfayllarni oson va tez o\'zgartiring.',
      'onboarding_title_2': 'Ko\'plab formatlarni\ndastlab qo\'llab-quvvatlaydi',
      'onboarding_subtitle_2': 'PDF, DOCX, JPG, PNG, MP4, MP3\nva yana ko\'plab formatlar.',
      'onboarding_title_3': 'Xavfsiz va shaxsiy',
      'onboarding_subtitle_3': 'Fayllaringiz qurilmangizda saqlanadi.\nHech kim ko\'ra olmaydi.',
      'onboarding_title_4': 'Tez va samarali',
      'onboarding_subtitle_4': 'Konvertatsiya jarayoni juda tez\nva sifatni yo\'qotmaydi.',
      'onboarding_title_5': 'Oson va qulay\nfoydalanish',
      'onboarding_subtitle_5': 'Intuitiv dizayn va sodda boshqaruv\nbilan hamma uchun qulay.',
      'onboarding_title_6': 'Boshlashga tayyormisiz?',
      'onboarding_subtitle_6': 'Endi fayllaringizni oson, tez\nva xavfsiz konvertatsiya qiling!',
      'home_banner_title': 'Formatlarni\noson va tez\nkonvertatsiya qiling',
      'home_start': 'Boshlash',
      'home_conversion': 'Konvertatsiya',
      'home_recent': 'So\'nggi konvertatsiyalar',
      'home_all': 'Barchasi',
      'home_empty_history': 'Konvertatsiyalar tarixi mavjud emas',
      'home_just_now': 'Hozirgina',
      'home_min_ago': 'daqiqa oldin',
      'home_hours_ago': 'soat oldin',
      'home_days_ago': 'kun oldin',
      'home_add_favorite': 'Sevimliga qo\'shish',
      'home_remove_favorite': 'Sevimlidan o\'chirish',
      'home_delete': 'O\'chirish',
      'cat_documents': 'Hujjatlar',
      'cat_images': 'Rasmlar',
      'cat_audio': 'Audio',
      'cat_video': 'Video',
      'cat_others': 'Boshqalar',
      'cat_favorites': 'Yaqinlar',
      'fav_title': 'Yaqinlar',
      'fav_empty': 'Yaqinlar ro\'yxati bo\'sh',
      'fav_empty_subtitle': 'Fayllaringizni tezda topish uchun yulduzcha\nbilan belgilab qo\'ying.',
      'files_title': 'Fayllarim',
      'files_search': 'Qidirish...',
      'files_empty': 'Fayllar topilmadi',
      'files_empty_search': 'Qidiruv so\'rovingizga mos fayl topilmadi.',
      'files_empty_desc': 'Siz hali hech qanday faylni konvertatsiya qilmadingiz.',
      'file_not_found': 'Fayl topilmadi!',
      'open_file': 'Faylni ochish',
      'share': 'Ulashish',
      'profile_title': 'Profil',
      'profile_account': 'Hisob sozlamalari',
      'profile_account_demo': 'Hisob sozlamalari yaqin orada qo\'shiladi!',
      'profile_language': 'Til',
      'profile_dark_mode': 'Dark mode',
      'profile_help': 'Yordam markazi',
      'profile_feedback': 'Fikr bildirish',
      'profile_feedback_demo': 'Fikr-mulohazalaringiz uchun rahmat!',
      'profile_about': 'Ilova haqida',
      'profile_premium_title': 'FunSwap Premium',
      'profile_premium_subtitle': 'Premium imkoniyatlardan foydalaning',
      'profile_premium_get': 'Olish',
      'profile_premium_active': 'FunSwap Premium faollashtirildi (Demo!)',
      'select_language': 'Tilni tanlang',
      'settings_title': 'Sozlamalar',
      'settings_general': 'Umumiy',
      'settings_other': 'Boshqalar',
      'settings_notifications': 'Bildirishnomalar',
      'settings_storage': 'Saqlash joyi',
      'settings_auto_delete': 'Avtomatik o\'chirish',
      'settings_cache': 'Keshni tozalash',
      'settings_cache_cleared': 'Kesh tozalandi!',
      'settings_privacy': 'Maxfiylik siyosati',
      'settings_terms': 'Foydalanish shartlari',
      'settings_delete_account': 'Hisobni o\'chirish',
      'settings_storage_title': 'Saqlash joyini tanlang',
      'settings_storage_internal': 'Ichki xotira',
      'settings_storage_sd': 'Tashqi SD karta',
      'settings_auto_delete_title': 'Avtomatik o\'chirish muddati',
      'settings_delete_never': 'Hech qachon',
      'settings_delete_1d': '1 kun',
      'settings_delete_7d': '7 kun',
      'settings_delete_30d': '30 kun',
      'settings_delete_confirm_title': 'Hisobni o\'chirish',
      'settings_delete_confirm_desc': 'Haqiqatdan ham hisobingizni butunlay o\'chirib tashlamoqchimisiz? Barcha ma\'lumotlar qaytarib bo\'lmaydigan qilib o\'chiriladi.',
      'cancel': 'Bekor qilish',
      'delete': 'O\'chirish',
      'account_deleted': 'Hisob o\'chirildi',
      'conversion_title': 'Konvertatsiya',
      'select_input_file': 'faylini tanlang',
      'conversion_error': 'Konvertatsiya xatosi',
      'save_error': 'Saqlashda xatolik yuz berdi',
      'file_saved': 'Fayl muvaffaqiyatli saqlandi',
      'select_save_location': 'Faylni saqlash joyini tanlang',
      'converting': 'Konvertatsiya qilinmoqda...',
      'please_wait': 'Iltimos kuting, bu biroz vaqt olishi mumkin',
      'conversion_success': 'Muvaffaqiyatli yakunlandi!',
      'file_name': 'Fayl nomi',
      'file_size': 'Fayl hajmi',
      'share_file': 'Ulashish',
      'save_to_device': 'Qurilmaga saqlash',
      'convert_another': 'Yana konvertatsiya qilish',
      'from': 'Dan',
      'to': 'Ga',
      'select_file_btn': 'Fayl tanlash',
      'recent_conversions': 'So\'nggi konvertatsiyalar',
      'start_conversion': 'Konvertatsiyani boshlash',
      'select_file': 'Faylni tanlang',
      'pick_system': 'Tizimdan tanlash',
      'selected_count': 'Tanlandi',
      'no_files': 'Mos fayllar topilmadi',
      'no_files_desc': 'Tizimdan tanlash tugmasi orqali telefoningizdan istalgan faylni yuklang.',
      'file_too_large_title': 'Fayl juda katta',
      'file_too_large_desc': 'Tanlangan fayl tavsiya etilgan hajmdan katta. Bu dasturning sekinlashishiga yoki o\'z-o\'zidan yopilishiga olib kelishi mumkin. Davom etishni xohlaysizmi?',
      'proceed_anyway': 'Baribir davom etish',
    },
    keyEn: {
      'tab_home': 'Home',
      'tab_files': 'Files',
      'tab_favorites': 'Favorites',
      'tab_profile': 'Profile',
      'loading': 'Loading...',
      'file_converter': 'File Converter',
      'onboarding_skip': 'Skip',
      'onboarding_next': 'Next',
      'onboarding_start': 'Start',
      'onboarding_title_1': 'Convert files to\nany format',
      'onboarding_subtitle_1': 'Easily and quickly change documents, images, audio, video and other files.',
      'onboarding_title_2': 'Supports many formats out of the box',
      'onboarding_subtitle_2': 'PDF, DOCX, JPG, PNG, MP4, MP3 and many more formats.',
      'onboarding_title_3': 'Secure and private',
      'onboarding_subtitle_3': 'Your files are kept on your device. Nobody else can access them.',
      'onboarding_title_4': 'Fast and efficient',
      'onboarding_subtitle_4': 'The conversion process is extremely fast and preserves high quality.',
      'onboarding_title_5': 'Simple and easy\nto use',
      'onboarding_subtitle_5': 'Intuitive design and simple controls make it accessible for everyone.',
      'onboarding_title_6': 'Ready to start?',
      'onboarding_subtitle_6': 'Now convert your files easily, quickly and securely!',
      'home_banner_title': 'Convert formats\neasily and quickly',
      'home_start': 'Start',
      'home_conversion': 'Conversion',
      'home_recent': 'Recent Conversions',
      'home_all': 'All',
      'home_empty_history': 'No conversion history available',
      'home_just_now': 'Just now',
      'home_min_ago': 'minutes ago',
      'home_hours_ago': 'hours ago',
      'home_days_ago': 'days ago',
      'home_add_favorite': 'Add to Favorites',
      'home_remove_favorite': 'Remove from Favorites',
      'home_delete': 'Delete',
      'cat_documents': 'Documents',
      'cat_images': 'Images',
      'cat_audio': 'Audio',
      'cat_video': 'Video',
      'cat_others': 'Others',
      'cat_favorites': 'Favorites',
      'fav_title': 'Favorites',
      'fav_empty': 'Favorites list is empty',
      'fav_empty_subtitle': 'Mark your files with a star to quickly find them here.',
      'files_title': 'My Files',
      'files_search': 'Search...',
      'files_empty': 'No files found',
      'files_empty_search': 'No file matches your search query.',
      'files_empty_desc': 'You have not converted any files yet.',
      'file_not_found': 'File not found!',
      'open_file': 'Open File',
      'share': 'Share',
      'profile_title': 'Profile',
      'profile_account': 'Account Settings',
      'profile_account_demo': 'Account settings will be added soon!',
      'profile_language': 'Language',
      'profile_dark_mode': 'Dark mode',
      'profile_help': 'Help Center',
      'profile_feedback': 'Feedback',
      'profile_feedback_demo': 'Thank you for your feedback!',
      'profile_about': 'About App',
      'profile_premium_title': 'FunSwap Premium',
      'profile_premium_subtitle': 'Use all premium features',
      'profile_premium_get': 'Get',
      'profile_premium_active': 'FunSwap Premium activated (Demo!)',
      'select_language': 'Select Language',
      'settings_title': 'Settings',
      'settings_general': 'General',
      'settings_other': 'Others',
      'settings_notifications': 'Notifications',
      'settings_storage': 'Storage Location',
      'settings_auto_delete': 'Auto Delete',
      'settings_cache': 'Clear Cache',
      'settings_cache_cleared': 'Cache cleared!',
      'settings_privacy': 'Privacy Policy',
      'settings_terms': 'Terms of Use',
      'settings_delete_account': 'Delete Account',
      'settings_storage_title': 'Select storage location',
      'settings_storage_internal': 'Internal storage',
      'settings_storage_sd': 'External SD card',
      'settings_auto_delete_title': 'Auto delete period',
      'settings_delete_never': 'Never',
      'settings_delete_1d': '1 day',
      'settings_delete_7d': '7 days',
      'settings_delete_30d': '30 days',
      'settings_delete_confirm_title': 'Delete Account',
      'settings_delete_confirm_desc': 'Are you sure you want to delete your account permanently? All data will be deleted irreversibly.',
      'cancel': 'Cancel',
      'delete': 'Delete',
      'account_deleted': 'Account deleted',
      'conversion_title': 'Conversion',
      'select_input_file': 'select file',
      'conversion_error': 'Conversion error',
      'save_error': 'Error occurred while saving',
      'file_saved': 'File saved successfully',
      'select_save_location': 'Select file save location',
      'converting': 'Converting...',
      'please_wait': 'Please wait, this may take a moment',
      'conversion_success': 'Successfully completed!',
      'file_name': 'File name',
      'file_size': 'File size',
      'share_file': 'Share',
      'save_to_device': 'Save to device',
      'convert_another': 'Convert another',
      'from': 'From',
      'to': 'To',
      'select_file_btn': 'Select File',
      'recent_conversions': 'Recent conversions',
      'start_conversion': 'Start Conversion',
      'select_file': 'Select File',
      'pick_system': 'Choose from system',
      'selected_count': 'Selected',
      'no_files': 'No matching files found',
      'no_files_desc': 'Upload any file from your phone using the choose from system button.',
      'file_too_large_title': 'File is Too Large',
      'file_too_large_desc': 'The selected file is larger than the recommended limit. This might cause performance issues or app crashes. Do you want to proceed?',
      'proceed_anyway': 'Proceed Anyway',
    },
    keyRu: {
      'tab_home': 'Главная',
      'tab_files': 'Файлы',
      'tab_favorites': 'Избранное',
      'tab_profile': 'Профиль',
      'loading': 'Загрузка...',
      'file_converter': 'Конвертер Файлов',
      'onboarding_skip': 'Пропустить',
      'onboarding_next': 'Далее',
      'onboarding_start': 'Начать',
      'onboarding_title_1': 'Конвертируйте файлы\nв любой формат',
      'onboarding_subtitle_1': 'Легко и быстро меняйте документы, изображения, аудио, видео и другие файлы.',
      'onboarding_title_2': 'Поддержка множества форматов из коробки',
      'onboarding_subtitle_2': 'PDF, DOCX, JPG, PNG, MP4, MP3 и многие другие форматы.',
      'onboarding_title_3': 'Безопасно и приватно',
      'onboarding_subtitle_3': 'Ваши файлы хранятся на вашем устройстве. Никто другой не имеет к ним доступа.',
      'onboarding_title_4': 'Быстро и эффективно',
      'onboarding_subtitle_4': 'Процесс конвертации происходит очень быстро и без потери качества.',
      'onboarding_title_5': 'Просто и удобно\nв использовании',
      'onboarding_subtitle_5': 'Интуитивно понятный дизайн и простое управление делают приложение удобным для всех.',
      'onboarding_title_6': 'Готовы начать?',
      'onboarding_subtitle_6': 'Теперь конвертируйте свои файлы легко, быстро и безопасно!',
      'home_banner_title': 'Конвертируйте форматы\nлегко и быстро',
      'home_start': 'Начать',
      'home_conversion': 'Конвертация',
      'home_recent': 'Последние конвертации',
      'home_all': 'Все',
      'home_empty_history': 'История конверсий пуста',
      'home_just_now': 'Только что',
      'home_min_ago': 'минут назад',
      'home_hours_ago': 'часов назад',
      'home_days_ago': 'дней назад',
      'home_add_favorite': 'Добавить в избранное',
      'home_remove_favorite': 'Удалить из избранного',
      'home_delete': 'Удалить',
      'cat_documents': 'Документы',
      'cat_images': 'Изображения',
      'cat_audio': 'Аудио',
      'cat_video': 'Видео',
      'cat_others': 'Другие',
      'cat_favorites': 'Избранное',
      'fav_title': 'Избранное',
      'fav_empty': 'Список избранного пуст',
      'fav_empty_subtitle': 'Пометьте свои файлы звездочкой, чтобы быстро находить их здесь.',
      'files_title': 'Мои файлы',
      'files_search': 'Поиск...',
      'files_empty': 'Файлы не найдены',
      'files_empty_search': 'Файл по вашему запросу не найден.',
      'files_empty_desc': 'Вы еще не конвертировали ни одного файла.',
      'file_not_found': 'Файл не найден!',
      'open_file': 'Открыть файл',
      'share': 'Поделиться',
      'profile_title': 'Профиль',
      'profile_account': 'Настройки аккаунта',
      'profile_account_demo': 'Настройки аккаунта будут добавлены в ближайшее время!',
      'profile_language': 'Язык',
      'profile_dark_mode': 'Темный режим',
      'profile_help': 'Центр помощи',
      'profile_feedback': 'Оставить отзыв',
      'profile_feedback_demo': 'Спасибо за ваш отзыв!',
      'profile_about': 'О приложении',
      'profile_premium_title': 'FunSwap Premium',
      'profile_premium_subtitle': 'Используйте премиум-возможности',
      'profile_premium_get': 'Получить',
      'profile_premium_active': 'FunSwap Premium активирован (Демо!)',
      'select_language': 'Выберите язык',
      'settings_title': 'Настройки',
      'settings_general': 'Общие',
      'settings_other': 'Другие',
      'settings_notifications': 'Уведомления',
      'settings_storage': 'Место хранения',
      'settings_auto_delete': 'Автоудаление',
      'settings_cache': 'Очистить кэш',
      'settings_cache_cleared': 'Кэш очищен!',
      'settings_privacy': 'Политика конфиденциальности',
      'settings_terms': 'Условия использования',
      'settings_delete_account': 'Удалить аккаунт',
      'settings_storage_title': 'Выберите место хранения',
      'settings_storage_internal': 'Внутренняя память',
      'settings_storage_sd': 'Внешняя SD-карта',
      'settings_auto_delete_title': 'Срок автоматического удаления',
      'settings_delete_never': 'Никогда',
      'settings_delete_1d': '1 день',
      'settings_delete_7d': '7 дней',
      'settings_delete_30d': '30 дней',
      'settings_delete_confirm_title': 'Удалить аккаунт',
      'settings_delete_confirm_desc': 'Вы действительно хотите навсегда удалить свой аккаунт? Все данные будут безвозвратно удалены.',
      'cancel': 'Отмена',
      'delete': 'Удалить',
      'account_deleted': 'Аккаунт удален',
      'conversion_title': 'Конвертация',
      'select_input_file': 'выберите файл',
      'conversion_error': 'Ошибка конвертации',
      'save_error': 'Произошла ошибка при сохранении',
      'file_saved': 'Файл успешно сохранен',
      'select_save_location': 'Выберите место для сохранения файла',
      'converting': 'Конвертирование...',
      'please_wait': 'Пожалуйста, подождите, это может занять время',
      'conversion_success': 'Успешно завершено!',
      'file_name': 'Имя файла',
      'file_size': 'Размер файла',
      'share_file': 'Поделиться',
      'save_to_device': 'Сохранить на устройство',
      'convert_another': 'Конвертировать еще',
      'from': 'Из',
      'to': 'В',
      'select_file_btn': 'Выбрать файл',
      'recent_conversions': 'Последние конверсии',
      'start_conversion': 'Начать конвертацию',
      'select_file': 'Выберите файл',
      'pick_system': 'Выбрать из системы',
      'selected_count': 'Выбрано',
      'no_files': 'Подходящие файлы не найдены',
      'no_files_desc': 'Загрузите любой файл с телефона с помощью кнопки выбора из системы.',
      'file_too_large_title': 'Файл слишком большой',
      'file_too_large_desc': 'Выбранный файл больше рекомендуемого размера. Это может привести к замедлению работы или сбою приложения. Вы действительно хотите продолжить?',
      'proceed_anyway': 'Всё равно продолжить',
    },
  };

  static String translate(String key) {
    final lang = appLanguageNotifier.value;
    return _translations[lang]?[key] ?? _translations[keyEn]?[key] ?? key;
  }

  static Future<void> loadLanguage() async {
    appLanguageNotifier.value = PreferencesService.getLanguage();
  }

  static Future<void> updateLanguage(String lang) async {
    appLanguageNotifier.value = lang;
    await PreferencesService.setLanguage(lang);
  }
}

extension LocalizationExtension on String {
  String get tr => LocalizationService.translate(this);
}
